services:
  db:
    image: postgres:15
    container_name: nest_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      JWT_SECRET: yourStrongSecretKeyHere
    depends_on:
      - db
    command: >
      sh -c "
        until pg_isready -h db -p 5432 -U postgres; do
          echo 'Waiting for Postgres...';
          sleep 2;
        done &&
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run start:prod
      "

volumes:
  db_data:
